"""Ports, value types, options models and errors.

This package imports nothing else from the library, no agent framework and no
cloud SDK. Everything else depends on it.
"""

from ai_agent_lib_core.contracts.access import Access, AccessQuery, AccessRule, no_access
from ai_agent_lib_core.contracts.audit import AUDIT_SCHEMA, AuditOutcome, AuditRecord, AuditValue
from ai_agent_lib_core.contracts.checks import CheckResult, generic_fix
from ai_agent_lib_core.contracts.data import (
    MASK,
    DataSource,
    Obligations,
    ParameterType,
    QueryDescription,
    QueryParameter,
    QueryResult,
    RowFilter,
    Scalar,
    SourceMetadata,
)
from ai_agent_lib_core.contracts.errors import (
    AgentLibError,
    BudgetExceeded,
    ConfigurationError,
    CredentialsExpiredError,
    ExecutionPaused,
    IntegrityError,
    PolicyDenied,
    TransientError,
    ValidationFailed,
    causes,
    describe,
    kind_of,
    shown_value,
)
from ai_agent_lib_core.contracts.guardrails import (
    GuardrailCheck,
    GuardrailFinding,
    GuardrailPoint,
    GuardrailVerdict,
)
from ai_agent_lib_core.contracts.identity import (
    Classification,
    Principal,
    PrincipalKind,
    RequestContext,
)
from ai_agent_lib_core.contracts.options import (
    DEFAULT_MODEL_ALIAS,
    AuditOptions,
    BudgetLimits,
    CallLimits,
    DeploymentEnv,
    ExternalSettings,
    Limits,
    ModelRef,
    ModelSection,
    NoOptions,
    OptionsModel,
    Profile,
    ProviderSelection,
    Section,
    ServiceConfig,
    TelemetryMode,
    options_error,
)
from ai_agent_lib_core.contracts.policy import (
    DECISION_SCHEMA,
    Decision,
    PolicyAction,
    PolicyDecisionPoint,
    PolicyRequest,
    PolicyResource,
)
from ai_agent_lib_core.contracts.ports import (
    AuditSink,
    ChatModelProvider,
    CheckpointBackend,
    Clock,
    ConfigSource,
    IdentityVerifier,
    IdGenerator,
    ModelCapabilities,
    SecretsProvider,
    SpanNotes,
    SupportsAsyncClose,
    SupportsValidation,
    Telemetry,
    TokenAuthenticator,
    TokenExchanger,
)
from ai_agent_lib_core.contracts.registry import (
    REGISTRY_SCHEMA,
    AgentEntry,
    AgentRegistry,
    AgentSnapshot,
    EntryStatus,
    RegistrySource,
    ServerEntry,
    ToolEntry,
    ToolRegistry,
    ToolSnapshot,
    schema_fingerprint,
)
from ai_agent_lib_core.contracts.scope import Scope
from ai_agent_lib_core.contracts.structured import StructuredOutput

__all__ = [
    "AUDIT_SCHEMA",
    "DECISION_SCHEMA",
    "DEFAULT_MODEL_ALIAS",
    "MASK",
    "REGISTRY_SCHEMA",
    "Access",
    "AccessQuery",
    "AccessRule",
    "AgentEntry",
    "AgentLibError",
    "AgentRegistry",
    "AgentSnapshot",
    "AuditOptions",
    "AuditOutcome",
    "AuditRecord",
    "AuditSink",
    "AuditValue",
    "BudgetExceeded",
    "BudgetLimits",
    "CallLimits",
    "ChatModelProvider",
    "CheckResult",
    "CheckpointBackend",
    "Classification",
    "Clock",
    "ConfigSource",
    "ConfigurationError",
    "CredentialsExpiredError",
    "DataSource",
    "Decision",
    "DeploymentEnv",
    "EntryStatus",
    "ExecutionPaused",
    "ExternalSettings",
    "GuardrailCheck",
    "GuardrailFinding",
    "GuardrailPoint",
    "GuardrailVerdict",
    "IdGenerator",
    "IdentityVerifier",
    "IntegrityError",
    "Limits",
    "ModelCapabilities",
    "ModelRef",
    "ModelSection",
    "NoOptions",
    "Obligations",
    "OptionsModel",
    "ParameterType",
    "PolicyAction",
    "PolicyDecisionPoint",
    "PolicyDenied",
    "PolicyRequest",
    "PolicyResource",
    "Principal",
    "PrincipalKind",
    "Profile",
    "ProviderSelection",
    "QueryDescription",
    "QueryParameter",
    "QueryResult",
    "RegistrySource",
    "RequestContext",
    "RowFilter",
    "Scalar",
    "Scope",
    "SecretsProvider",
    "Section",
    "ServerEntry",
    "ServiceConfig",
    "SourceMetadata",
    "SpanNotes",
    "StructuredOutput",
    "SupportsAsyncClose",
    "SupportsValidation",
    "Telemetry",
    "TelemetryMode",
    "TokenAuthenticator",
    "TokenExchanger",
    "ToolEntry",
    "ToolRegistry",
    "ToolSnapshot",
    "TransientError",
    "ValidationFailed",
    "causes",
    "describe",
    "generic_fix",
    "kind_of",
    "no_access",
    "options_error",
    "schema_fingerprint",
    "shown_value",
]
